
CREATE TABLE [AD_GROUPS](
	[ad_group_id] [bigint] IDENTITY(1,1) NOT NULL,
	[name] [varchar](150) NOT NULL,
	[administrator] bit NOT NULL,
 CONSTRAINT [PK_AD_GROUPS_1] PRIMARY KEY CLUSTERED 
(
	[ad_group_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [AD_GROUPS_PERMISSIONS](
	[ad_group_permission_id] [bigint] IDENTITY(1,1) NOT NULL,
	[ad_group_id] [bigint] NOT NULL,
	[permission_id] [bigint] NOT NULL,
 CONSTRAINT [PK_AD_GROUPS_PERMISSIONS] PRIMARY KEY CLUSTERED 
(
	[ad_group_permission_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [COUNTRIES](
	[country_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[prefix_number] [int] NOT NULL,
 CONSTRAINT [PK_COUNTRIES] PRIMARY KEY CLUSTERED 
(
	[country_id] ASC
	[country_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [DATATYPES](
	[datatype_id] [int] NOT NULL,
	[name] [varchar](50) NOT NULL,
	[typename] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DATATYPES] PRIMARY KEY CLUSTERED 
(
	[datatype_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [PERMISSIONS](
	[permission_id] [bigint] NOT NULL,
	[description] [varchar](150) NOT NULL,
	[name] [varchar](30) NOT NULL,
 CONSTRAINT [PK_PERMISSIONS] PRIMARY KEY CLUSTERED 
(
	[permission_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [SYSTEMS_FUNCTIONALITIES](
	[system_functionality_id] [bigint] IDENTITY(1,1) NOT NULL,
	[description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_SYSTEMS_FUNCTIONALITIES] PRIMARY KEY CLUSTERED 
(
	[system_functionality_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [SYSTEMS_RECORDS](
	[system_record_id] [bigint] IDENTITY(1,1) NOT NULL,
	[system_functionality_id] [bigint] NOT NULL,
	[date_time] [datetime] NOT NULL,
	[user_id] [bigint] NULL,
	[id] [bigint] NULL,
	[description] [varchar](8000) NOT NULL,
	[comments] [varchar](500) NULL,

 CONSTRAINT [PK_SYSTEMS_RECORDS] PRIMARY KEY CLUSTERED 
(
	[system_record_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [LANGUAGES](
	[language_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NULL,
	[code] [varchar](50) NULL,
	[country_id] [int] NOT NULL,
 CONSTRAINT [PK_LANGUAGES] PRIMARY KEY CLUSTERED 
(
	[language_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [USERS](
	[user_id] [bigint] IDENTITY(1,1) NOT NULL,
	[initials] [varchar](4) NOT NULL,
	[deactivated] [bit] NOT NULL,
	[datetime_deactivate] [datetime] NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];




ALTER TABLE [AD_GROUPS_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_AD_GROUPS_PERMISSIONS_AD_GROUPS1] FOREIGN KEY([ad_group_id])
REFERENCES [AD_GROUPS] ([ad_group_id]);

ALTER TABLE [AD_GROUPS_PERMISSIONS] CHECK CONSTRAINT [FK_AD_GROUPS_PERMISSIONS_AD_GROUPS1];

ALTER TABLE [AD_GROUPS_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_AD_GROUPS_PERMISSIONS_PERMISSIONS] FOREIGN KEY([permission_id])
REFERENCES [PERMISSIONS] ([permission_id]);

ALTER TABLE [AD_GROUPS_PERMISSIONS] CHECK CONSTRAINT [FK_AD_GROUPS_PERMISSIONS_PERMISSIONS];

ALTER TABLE [SYSTEMS_RECORDS]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEMS_RECORDS_SYSTEMS_FUNCTIONALITIES] FOREIGN KEY([system_functionality_id])
REFERENCES [SYSTEMS_FUNCTIONALITIES] ([system_functionality_id]);

ALTER TABLE [SYSTEMS_RECORDS] CHECK CONSTRAINT [FK_SYSTEMS_RECORDS_SYSTEMS_FUNCTIONALITIES];

ALTER TABLE [SYSTEMS_RECORDS]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEMS_RECORDS_USERS] FOREIGN KEY([user_id])
REFERENCES [USERS] ([user_id]);

ALTER TABLE [SYSTEMS_RECORDS] CHECK CONSTRAINT [FK_SYSTEMS_RECORDS_USERS];

ALTER TABLE [LANGUAGES]  WITH CHECK ADD  CONSTRAINT [FK_LANGUAGES_COUNTRIES1] FOREIGN KEY([country_id])
REFERENCES [COUNTRIES] ([country_id]);

ALTER TABLE [LANGUAGES] CHECK CONSTRAINT [FK_LANGUAGES_COUNTRIES1];

ALTER TABLE dbo.USERS ADD language_id int NULL;

ALTER TABLE dbo.USERS ADD CONSTRAINT FK_USERS_LANGUAGES FOREIGN KEY (language_id) REFERENCES dbo.LANGUAGES (language_id) ON UPDATE  NO ACTION ON DELETE  NO ACTION;

CREATE TABLE [AD_GROUPS_USERS](
	[ad_group_user_id] [bigint] identity(1,1) NOT NULL,
	[ad_group_id] [bigint] NOT NULL,
	[user_id] [bigint] NULL,
	 CONSTRAINT [PK_GROUPS_USERS] PRIMARY KEY CLUSTERED 
	(
		[ad_group_user_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];


ALTER TABLE [AD_GROUPS_USERS]  WITH CHECK ADD  CONSTRAINT [FK_AD_GROUPS_USERS_GROUPS] FOREIGN KEY([ad_group_id])
REFERENCES [AD_GROUPS] ([ad_group_id]);


ALTER TABLE [AD_GROUPS_USERS] CHECK CONSTRAINT [FK_AD_GROUPS_USERS_GROUPS];


ALTER TABLE [AD_GROUPS_USERS]  WITH CHECK ADD  CONSTRAINT [FK_GROUPS_USERS_USERS] FOREIGN KEY([user_id])
REFERENCES [USERS] ([user_id]);


ALTER TABLE [AD_GROUPS_USERS] CHECK CONSTRAINT [FK_GROUPS_USERS_USERS];




CREATE TABLE [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES](
	[block_version_checklist_template_id] [bigint] IDENTITY(1,1) NOT NULL,
	[version_checklist_template_id] [bigint] NOT NULL,
	[position] [int] NOT NULL,
	[title] [varchar](150) NOT NULL,
	[parent_block_version_checklist_template_id] [bigint] NULL,
 CONSTRAINT [PK_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[block_version_checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [CANCELLED_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES](
	[cancelled_item_version_checklist_template_id] [bigint] NOT NULL,
	[option_item_version_checklist_template_id] [bigint] NOT NULL,
	[target_item_version_checklist_template_id] [bigint] NOT NULL,
 CONSTRAINT [PK_CANCELLED_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[cancelled_item_version_checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [CHECKLISTS](
	[checklist_id] [bigint] IDENTITY(1,1) NOT NULL,
	[version_checklist_template_id] [bigint] NOT NULL,
	[creation_timestamp] [datetime] NOT NULL,
	[creation_user_id] [bigint] NOT NULL,
	[update_timestamp] [datetime] NULL,
	[update_user_id] [bigint] NULL,
 CONSTRAINT [PK_CHECKLISTS] PRIMARY KEY CLUSTERED 
(
	[checklist_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [CHECKLISTS_TEMPLATES](
	[checklist_template_id] [bigint] IDENTITY(1,1) NOT NULL,
	[description] [varchar](100) NOT NULL,
 CONSTRAINT [PK_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [COMMENTS_CHECKLISTS](
	[comment_checklist_id] [bigint] IDENTITY(1,1) NOT NULL,
	[checklist_id] [bigint] NOT NULL,
	[stamp] [varchar](500) NOT NULL,
	[comments] [varchar](5000) NOT NULL,
	[creation_timestamp] [datetime] NOT NULL,
	[creation_user_id] [bigint] NOT NULL,
 CONSTRAINT [PK_COMMENTS_CHECKLISTS] PRIMARY KEY CLUSTERED 
(
	[comment_checklist_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES](
	[dependency_block_version_checklist_template_id] [bigint] IDENTITY(1,1) NOT NULL,
	[block_version_checklist_template_id] [bigint] NOT NULL,
	[dependent_block_version_checklist_template_id] [bigint] NULL,
	[dependent_item_version_checklist_template_id] [bigint] NULL,
 CONSTRAINT [PK_DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[dependency_block_version_checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES](
	[dependency_item_version_checklist_template_id] [bigint] IDENTITY(1,1) NOT NULL,
	[item_version_checklist_template_id] [bigint] NOT NULL,
	[dependent_block_version_checklist_template_id] [bigint] NULL,
	[dependent_item_version_checklist_template_id] [bigint] NULL,
 CONSTRAINT [PK_DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[dependency_item_version_checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [FIELDS_CHECKLISTS](
	[field_checklist_id] [bigint] IDENTITY(1,1) NOT NULL,
	[checklist_id] [bigint] NOT NULL,
	[field_version_checklist_template_id] [bigint] NOT NULL,
	[value] [varchar](1000) NULL,
	[option_field_version_checklist_template_id] [bigint] NULL,
	[creation_timestamp] [datetime] NOT NULL,
	[creation_user_id] [bigint] NOT NULL,
	[update_timestamp] [datetime] NULL,
	[update_user_id] [bigint] NULL,
 CONSTRAINT [PK_FIELDS_CHECKLISTS] PRIMARY KEY CLUSTERED 
(
	[field_checklist_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [FIELDS_DATA_TYPES](
	[field_data_type_id] [int] NOT NULL,
	[name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_FIELDS_DATA_TYPES] PRIMARY KEY CLUSTERED 
(
	[field_data_type_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [FIELDS_VERSIONS_CHECKLISTS_TEMPLATES](
	[field_version_checklist_template_id] [bigint] IDENTITY(1,1) NOT NULL,
	[version_checklist_template_id] [bigint] NOT NULL,
	[position] [int] NOT NULL,
	[title] [varchar](100) NOT NULL,
	[field_data_type_id] [int] NOT NULL,
	[regex_validation] [varchar](100) NULL,
	[format] [varchar](100) NULL,
	[mandatory] [bit] NOT NULL,
	[is_key] [bit] NOT NULL,
 CONSTRAINT [PK_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[field_version_checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [ITEMS_CHECKLISTS](
	[item_checklist_id] [bigint] IDENTITY(1,1) NOT NULL,
	[checklist_id] [bigint] NOT NULL,
	[item_version_checklist_template_id] [bigint] NOT NULL,
	[stamp] [varchar](500) NOT NULL,
	[creation_timestamp] [datetime] NOT NULL,
	[creation_user_id] [bigint] NOT NULL,
	[comments] [varchar](5000) NULL,
	[is_rejected] [bit] NULL,
 CONSTRAINT [PK_ITEMS_CHECKLISTS] PRIMARY KEY CLUSTERED 
(
	[item_checklist_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [ITEMS_TYPES](
	[item_type_id] [int] NOT NULL,
	[description] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ITEMS_TYPES] PRIMARY KEY CLUSTERED 
(
	[item_type_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES](
	[item_version_checklist_template_id] [bigint] IDENTITY(1,1) NOT NULL,
	[version_checklist_template_id] [bigint] NOT NULL,
	[position] [int] NOT NULL,
	[title] [varchar](500) NOT NULL,
	[item_type_id] [int] NOT NULL,
	[block_version_checklist_template_id] [bigint] NOT NULL,
	[option_field_version_checklist_template_id] [bigint] NULL,
	[options_title] [varchar](500) NULL,
 CONSTRAINT [PK_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[item_version_checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES](
	[option_field_version_checklist_template_id] [bigint] IDENTITY(1,1) NOT NULL,
	[field_version_checklist_template_id] [bigint] NOT NULL,
	[title] [varchar](50) NOT NULL,
	[value] [int] NOT NULL,
 CONSTRAINT [PK_OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[option_field_version_checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [OPTIONS_ITEMS_CHECKLISTS](
	[option_item_checklist_id] [bigint] IDENTITY(1,1) NOT NULL,
	[item_checklist_id] [bigint] NOT NULL,
	[option_item_version_checklist_template_id] [bigint] NOT NULL,
	[creation_timestamp] [datetime] NOT NULL,
	[creation_user_id] [bigint] NOT NULL,
 CONSTRAINT [PK_OPTIONS_ITEMS_CHECKLISTS] PRIMARY KEY CLUSTERED 
(
	[option_item_checklist_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES](
	[option_item_version_checklist_template_id] [bigint] IDENTITY(1,1) NOT NULL,
	[item_version_checklist_template_id] [bigint] NOT NULL,
	[title] [varchar](50) NOT NULL,
	[value] [int] NOT NULL,
 CONSTRAINT [PK_OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[option_item_version_checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [VERSIONS_CHECKLISTS_TEMPLATES](
	[version_checklist_template_id] [bigint] IDENTITY(1,1) NOT NULL,
	[checklist_template_id] [bigint] NOT NULL,
	[timestamp_creation] [datetime] NOT NULL,
	[timestamp_update] [datetime] NULL,
	[version] [varchar](10) NOT NULL,
	[creation_user_id] [bigint] NOT NULL,
	[update_user_id] [bigint] NULL,
 CONSTRAINT [PK_VERSIONS_CHECKLISTS_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[version_checklist_template_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];



ALTER TABLE [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([parent_block_version_checklist_template_id])
REFERENCES [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] ([block_version_checklist_template_id]);

ALTER TABLE [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([version_checklist_template_id])
REFERENCES [VERSIONS_CHECKLISTS_TEMPLATES] ([version_checklist_template_id]);

ALTER TABLE [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [CANCELLED_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_CANCELLED_OPTION_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([option_item_version_checklist_template_id])
REFERENCES [OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] ([option_item_version_checklist_template_id]);

ALTER TABLE [CANCELLED_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_CANCELLED_OPTION_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [CANCELLED_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_CANCELLED_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES1] FOREIGN KEY([target_item_version_checklist_template_id])
REFERENCES [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] ([item_version_checklist_template_id]);

ALTER TABLE [CANCELLED_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_CANCELLED_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES1];

ALTER TABLE [CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_CHECKLISTS_USERS] FOREIGN KEY([creation_user_id])
REFERENCES [USERS] ([user_id]);

ALTER TABLE [CHECKLISTS] CHECK CONSTRAINT [FK_CHECKLISTS_USERS];

ALTER TABLE [CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_CHECKLISTS_USERS1] FOREIGN KEY([update_user_id]) REFERENCES [USERS] ([user_id]);

ALTER TABLE [CHECKLISTS] CHECK CONSTRAINT [FK_CHECKLISTS_USERS1];

ALTER TABLE [CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_CHECKLISTS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([version_checklist_template_id])
REFERENCES [VERSIONS_CHECKLISTS_TEMPLATES] ([version_checklist_template_id]);

ALTER TABLE [CHECKLISTS] CHECK CONSTRAINT [FK_CHECKLISTS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [COMMENTS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_COMMENTS_CHECKLISTS_CHECKLISTS] FOREIGN KEY([checklist_id])
REFERENCES [CHECKLISTS] ([checklist_id]);

ALTER TABLE [COMMENTS_CHECKLISTS] CHECK CONSTRAINT [FK_COMMENTS_CHECKLISTS_CHECKLISTS];

ALTER TABLE [COMMENTS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_COMMENTS_CHECKLISTS_USERS] FOREIGN KEY([creation_user_id]) REFERENCES [USERS] ([user_id]);

ALTER TABLE [COMMENTS_CHECKLISTS] CHECK CONSTRAINT [FK_COMMENTS_CHECKLISTS_USERS];

ALTER TABLE [DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([block_version_checklist_template_id])
REFERENCES [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] ([block_version_checklist_template_id]);

ALTER TABLE [DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES1] FOREIGN KEY([dependent_block_version_checklist_template_id])
REFERENCES [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] ([block_version_checklist_template_id]);

ALTER TABLE [DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES1];

ALTER TABLE [DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([dependent_item_version_checklist_template_id])
REFERENCES [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] ([item_version_checklist_template_id]);

ALTER TABLE [DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_DEPENDENCIES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([dependent_block_version_checklist_template_id])
REFERENCES [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] ([block_version_checklist_template_id]);

ALTER TABLE [DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([item_version_checklist_template_id])
REFERENCES [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] ([item_version_checklist_template_id]);

ALTER TABLE [DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES1] FOREIGN KEY([dependent_item_version_checklist_template_id])
REFERENCES [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] ([item_version_checklist_template_id]);

ALTER TABLE [DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_DEPENDENCIES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES1];

ALTER TABLE [FIELDS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_FIELDS_CHECKLISTS_CHECKLISTS] FOREIGN KEY([checklist_id]) REFERENCES [CHECKLISTS] ([checklist_id]);

ALTER TABLE [FIELDS_CHECKLISTS] CHECK CONSTRAINT [FK_FIELDS_CHECKLISTS_CHECKLISTS];

ALTER TABLE [FIELDS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_FIELDS_CHECKLISTS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([field_version_checklist_template_id])
REFERENCES [FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] ([field_version_checklist_template_id]);

ALTER TABLE [FIELDS_CHECKLISTS] CHECK CONSTRAINT [FK_FIELDS_CHECKLISTS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [FIELDS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_FIELDS_CHECKLISTS_OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([option_field_version_checklist_template_id])
REFERENCES [OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] ([option_field_version_checklist_template_id]);

ALTER TABLE [FIELDS_CHECKLISTS] CHECK CONSTRAINT [FK_FIELDS_CHECKLISTS_OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [FIELDS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_FIELDS_CHECKLISTS_USERS] FOREIGN KEY([creation_user_id]) REFERENCES [USERS] ([user_id]);

ALTER TABLE [FIELDS_CHECKLISTS] CHECK CONSTRAINT [FK_FIELDS_CHECKLISTS_USERS];

ALTER TABLE [FIELDS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_FIELDS_CHECKLISTS_USERS1] FOREIGN KEY([update_user_id]) REFERENCES [USERS] ([user_id]);

ALTER TABLE [FIELDS_CHECKLISTS] CHECK CONSTRAINT [FK_FIELDS_CHECKLISTS_USERS1];

ALTER TABLE [FIELDS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES_FIELDS_DATA_TYPES] FOREIGN KEY([field_data_type_id])
REFERENCES [FIELDS_DATA_TYPES] ([field_data_type_id]);

ALTER TABLE [FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES_FIELDS_DATA_TYPES];

ALTER TABLE [FIELDS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([version_checklist_template_id])
REFERENCES [VERSIONS_CHECKLISTS_TEMPLATES] ([version_checklist_template_id]);

ALTER TABLE [FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [ITEMS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_ITEMS_CHECKLISTS_CHECKLISTS] FOREIGN KEY([checklist_id]) REFERENCES [CHECKLISTS] ([checklist_id]);

ALTER TABLE [ITEMS_CHECKLISTS] CHECK CONSTRAINT [FK_ITEMS_CHECKLISTS_CHECKLISTS];

ALTER TABLE [ITEMS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_ITEMS_CHECKLISTS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([item_version_checklist_template_id])
REFERENCES [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] ([item_version_checklist_template_id]);

ALTER TABLE [ITEMS_CHECKLISTS] CHECK CONSTRAINT [FK_ITEMS_CHECKLISTS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [ITEMS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_ITEMS_CHECKLISTS_USERS] FOREIGN KEY([creation_user_id])
REFERENCES [USERS] ([user_id]);

ALTER TABLE [ITEMS_CHECKLISTS] CHECK CONSTRAINT [FK_ITEMS_CHECKLISTS_USERS];

ALTER TABLE [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([block_version_checklist_template_id])
REFERENCES [BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES] ([block_version_checklist_template_id]);

ALTER TABLE [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_BLOCKS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_TYPES] FOREIGN KEY([item_type_id])
REFERENCES [ITEMS_TYPES] ([item_type_id]);

ALTER TABLE [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_TYPES];

ALTER TABLE [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([option_field_version_checklist_template_id])
REFERENCES [OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] ([option_field_version_checklist_template_id]);

ALTER TABLE [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([version_checklist_template_id])
REFERENCES [VERSIONS_CHECKLISTS_TEMPLATES] ([version_checklist_template_id]);

ALTER TABLE [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([field_version_checklist_template_id])
REFERENCES [FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] ([field_version_checklist_template_id]);

ALTER TABLE [OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_OPTIONS_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES_FIELDS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [OPTIONS_ITEMS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_OPTIONS_ITEMS_CHECKLISTS_ITEMS_CHECKLISTS] FOREIGN KEY([item_checklist_id])
REFERENCES [ITEMS_CHECKLISTS] ([item_checklist_id]);

ALTER TABLE [OPTIONS_ITEMS_CHECKLISTS] CHECK CONSTRAINT [FK_OPTIONS_ITEMS_CHECKLISTS_ITEMS_CHECKLISTS];

ALTER TABLE [OPTIONS_ITEMS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_OPTIONS_ITEMS_CHECKLISTS_OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([option_item_version_checklist_template_id])
REFERENCES [OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] ([option_item_version_checklist_template_id]);

ALTER TABLE [OPTIONS_ITEMS_CHECKLISTS] CHECK CONSTRAINT [FK_OPTIONS_ITEMS_CHECKLISTS_OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [OPTIONS_ITEMS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_OPTIONS_ITEMS_CHECKLISTS_USERS] FOREIGN KEY([creation_user_id])
REFERENCES [USERS] ([user_id]);

ALTER TABLE [OPTIONS_ITEMS_CHECKLISTS] CHECK CONSTRAINT [FK_OPTIONS_ITEMS_CHECKLISTS_USERS];

ALTER TABLE [OPTIONS_ITEMS_CHECKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_OPTIONS_ITEMS_CHECKLISTS_USERS1] FOREIGN KEY([creation_user_id])
REFERENCES [USERS] ([user_id]);

ALTER TABLE [OPTIONS_ITEMS_CHECKLISTS] CHECK CONSTRAINT [FK_OPTIONS_ITEMS_CHECKLISTS_USERS1];

ALTER TABLE [OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] FOREIGN KEY([item_version_checklist_template_id])
REFERENCES [ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] ([item_version_checklist_template_id]);

ALTER TABLE [OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_OPTIONS_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES_ITEMS_VERSIONS_CHECKLISTS_TEMPLATES];

ALTER TABLE [VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_VERSIONS_CHECKLISTS_TEMPLATES_CHECKLISTS_TEMPLATES] FOREIGN KEY([checklist_template_id])
REFERENCES [CHECKLISTS_TEMPLATES] ([checklist_template_id]);

ALTER TABLE [VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_VERSIONS_CHECKLISTS_TEMPLATES_CHECKLISTS_TEMPLATES];

ALTER TABLE [VERSIONS_CHECKLISTS_TEMPLATES]  WITH CHECK ADD  CONSTRAINT [FK_VERSIONS_CHECKLISTS_TEMPLATES_USERS] FOREIGN KEY([creation_user_id])
REFERENCES [USERS] ([user_id]);

ALTER TABLE [VERSIONS_CHECKLISTS_TEMPLATES] CHECK CONSTRAINT [FK_VERSIONS_CHECKLISTS_TEMPLATES_USERS];




