
CREATE TABLE [AD_GROUPS](
	[ad_group_id] [bigint] IDENTITY(1,1) NOT NULL,
	[name] [varchar](150) NOT NULL,
	[administrator] bit NOT NULL,
 CONSTRAINT [PK_AD_GROUPS_1] PRIMARY KEY CLUSTERED 
(
	[ad_group_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [AD_GROUPS_PERMISSIONS](
	[ad_group_permission_id] [bigint] IDENTITY(1,1) NOT NULL,
	[ad_group_id] [bigint] NOT NULL,
	[permission_id] [bigint] NOT NULL,
 CONSTRAINT [PK_AD_GROUPS_PERMISSIONS] PRIMARY KEY CLUSTERED 
(
	[ad_group_permission_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [COUNTRIES](
	[country_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[prefix_number] [int] NOT NULL,
 CONSTRAINT [PK_COUNTRIES] PRIMARY KEY CLUSTERED 
(
	[country_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [DATATYPES](
	[datatype_id] [int] NOT NULL,
	[name] [varchar](50) NOT NULL,
	[typename] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DATATYPES] PRIMARY KEY CLUSTERED 
(
	[datatype_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [PERMISSIONS](
	[permission_id] [bigint] NOT NULL,
	[description] [varchar](150) NOT NULL,
	[name] [varchar](30) NOT NULL,
 CONSTRAINT [PK_PERMISSIONS] PRIMARY KEY CLUSTERED 
(
	[permission_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [SYSTEMS_FUNCTIONALITIES](
	[system_functionality_id] [bigint] IDENTITY(1,1) NOT NULL,
	[description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_SYSTEMS_FUNCTIONALITIES] PRIMARY KEY CLUSTERED 
(
	[system_functionality_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [SYSTEMS_RECORDS](
	[system_record_id] [bigint] IDENTITY(1,1) NOT NULL,
	[system_functionality_id] [bigint] NOT NULL,
	[date_time] [datetime] NOT NULL,
	[user_id] [bigint] NULL,
	[id] [bigint] NULL,
	[description] [varchar](8000) NOT NULL,
 CONSTRAINT [PK_SYSTEMS_RECORDS] PRIMARY KEY CLUSTERED 
(
	[system_record_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [LANGUAGES](
	[language_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NULL,
	[code] [varchar](50) NULL,
	[country_id] [int] NOT NULL,
 CONSTRAINT [PK_LANGUAGES] PRIMARY KEY CLUSTERED 
(
	[language_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [USERS](
	[user_id] [bigint] IDENTITY(1,1) NOT NULL,
	[initials] [varchar](4) NOT NULL,
	[deactivated] [bit] NOT NULL,
	[datetime_deactivate] [datetime] NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];



ALTER TABLE [AD_GROUPS_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_AD_GROUPS_PERMISSIONS_AD_GROUPS1] FOREIGN KEY([ad_group_id])
REFERENCES [AD_GROUPS] ([ad_group_id]);

ALTER TABLE [AD_GROUPS_PERMISSIONS] CHECK CONSTRAINT [FK_AD_GROUPS_PERMISSIONS_AD_GROUPS1];

ALTER TABLE [AD_GROUPS_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_AD_GROUPS_PERMISSIONS_PERMISSIONS] FOREIGN KEY([permission_id])
REFERENCES [PERMISSIONS] ([permission_id]);

ALTER TABLE [AD_GROUPS_PERMISSIONS] CHECK CONSTRAINT [FK_AD_GROUPS_PERMISSIONS_PERMISSIONS];

ALTER TABLE [SYSTEMS_RECORDS]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEMS_RECORDS_SYSTEMS_FUNCTIONALITIES] FOREIGN KEY([system_functionality_id])
REFERENCES [SYSTEMS_FUNCTIONALITIES] ([system_functionality_id]);

ALTER TABLE [SYSTEMS_RECORDS] CHECK CONSTRAINT [FK_SYSTEMS_RECORDS_SYSTEMS_FUNCTIONALITIES];

ALTER TABLE [SYSTEMS_RECORDS]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEMS_RECORDS_USERS] FOREIGN KEY([user_id])
REFERENCES [USERS] ([user_id]);

ALTER TABLE [SYSTEMS_RECORDS] CHECK CONSTRAINT [FK_SYSTEMS_RECORDS_USERS];

ALTER TABLE [LANGUAGES]  WITH CHECK ADD  CONSTRAINT [FK_LANGUAGES_COUNTRIES1] FOREIGN KEY([country_id])
REFERENCES [COUNTRIES] ([country_id]);

ALTER TABLE [LANGUAGES] CHECK CONSTRAINT [FK_LANGUAGES_COUNTRIES1];

ALTER TABLE dbo.USERS ADD language_id int NULL;

ALTER TABLE dbo.USERS ADD CONSTRAINT FK_USERS_LANGUAGES FOREIGN KEY (language_id) REFERENCES dbo.LANGUAGES (language_id) ON UPDATE  NO ACTION ON DELETE  NO ACTION;

CREATE TABLE [AD_GROUPS_USERS](
	[ad_group_user_id] [bigint] identity(1,1) NOT NULL,
	[ad_group_id] [bigint] NOT NULL,
	[user_id] [bigint] NULL,
	 CONSTRAINT [PK_GROUPS_USERS] PRIMARY KEY CLUSTERED 
	(
		[ad_group_user_id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];


ALTER TABLE [AD_GROUPS_USERS]  WITH CHECK ADD  CONSTRAINT [FK_AD_GROUPS_USERS_GROUPS] FOREIGN KEY([ad_group_id])
REFERENCES [AD_GROUPS] ([ad_group_id]);


ALTER TABLE [AD_GROUPS_USERS] CHECK CONSTRAINT [FK_AD_GROUPS_USERS_GROUPS];


ALTER TABLE [AD_GROUPS_USERS]  WITH CHECK ADD  CONSTRAINT [FK_GROUPS_USERS_USERS] FOREIGN KEY([user_id])
REFERENCES [USERS] ([user_id]);


ALTER TABLE [AD_GROUPS_USERS] CHECK CONSTRAINT [FK_GROUPS_USERS_USERS];
