
INSERT INTO countries (name, prefix_number) values ('Brasil', 55);
INSERT INTO countries (name, prefix_number) values ('Estados unidos', 60);

INSERT INTO SYSTEMS_FUNCTIONALITIES (DESCRIPTION) VALUES ('SYSTEMS_ACCESSES');
INSERT INTO SYSTEMS_FUNCTIONALITIES (DESCRIPTION) VALUES ('PARAMETERS');
INSERT INTO SYSTEMS_FUNCTIONALITIES (DESCRIPTION) VALUES ('USERS');
INSERT INTO SYSTEMS_FUNCTIONALITIES (DESCRIPTION) VALUES ('PERMISSIONS');
INSERT INTO SYSTEMS_FUNCTIONALITIES (DESCRIPTION) VALUES ('GENERAL_REGISTRATIONS');


INSERT INTO PERMISSIONS (PERMISSION_ID, DESCRIPTION, NAME) VALUES (1, 'Manage parameters', 'MANAGE_PARAMETER');
INSERT INTO PERMISSIONS (PERMISSION_ID, DESCRIPTION, NAME) VALUES (2, 'Manage groups', 'MANAGE_GROUPS');
INSERT INTO PERMISSIONS (PERMISSION_ID, DESCRIPTION, NAME) VALUES (3, 'Manage countries areas and area phones', 'MANAGE_LOCALIZATION');
INSERT INTO PERMISSIONS (PERMISSION_ID, DESCRIPTION, NAME) VALUES (4, 'Manage users', 'MANAGE_USERS');
INSERT INTO PERMISSIONS (PERMISSION_ID, DESCRIPTION, NAME) VALUES (5, 'Manage Areas', 'MANAGE_AREAS');
INSERT INTO PERMISSIONS (PERMISSION_ID, DESCRIPTION, NAME) VALUES (6, 'Manage Checklists', 'CHECKLISTS');
INSERT INTO PERMISSIONS (PERMISSION_ID, DESCRIPTION, NAME) VALUES (7, 'Manage Validations', 'VALIDATIONS');

INSERT INTO AD_GROUPS (NAME, administrator) VALUES ('nsrm_admin', 1);
INSERT INTO AD_GROUPS (NAME, administrator) VALUES ('nsrm_manutencao', 0);
INSERT INTO AD_GROUPS (NAME, administrator) VALUES ('nsrm_avaliador', 0);
INSERT INTO AD_GROUPS (NAME, administrator) VALUES ('nsrm_qa', 0);

INSERT INTO AD_GROUPS_PERMISSIONS (AD_GROUP_ID, PERMISSION_ID) VALUEs (2, 1);
INSERT INTO AD_GROUPS_PERMISSIONS (AD_GROUP_ID, PERMISSION_ID) VALUEs (2, 1);
INSERT INTO AD_GROUPS_PERMISSIONS (AD_GROUP_ID, PERMISSION_ID) VALUEs (2, 2);
INSERT INTO AD_GROUPS_PERMISSIONS (AD_GROUP_ID, PERMISSION_ID) VALUEs (2, 3);

INSERT INTO  LANGUAGES (NAME, CODE, COUNTRY_ID) VALUES ('Português', 'pt-BR', 1);
INSERT INTO  LANGUAGES (NAME, CODE, COUNTRY_ID) VALUES ('Inglês', 'en-US', 2);

insert into users (initials, deactivated, datetime_deactivate, language_id) values ('_adm', 0, null, 1);
